version: "3.8"

services:
  api:
    build: .
    container_name: flask_api
    ports:
      - "5000:5000"
    volumes:
      - ./src/static:/app/static
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=qr_code_db
    depends_on:
      - db

  db:
    image: mysql:8
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./init_db.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  db_data:
